DROP TABLE IF EXISTS request_map CASCADE;
DROP TABLE IF EXISTS user_authority CASCADE;
DROP TABLE IF EXISTS menu_authority CASCADE;
DROP TABLE IF EXISTS authority CASCADE;
DROP TABLE IF EXISTS menu_attr CASCADE;
DROP TABLE IF EXISTS menu CASCADE;
DROP TABLE IF EXISTS user CASCADE;