package com.mybatis.core.domain;

import com.mybatis.common.domain.BaseDomain;

public class Authority extends BaseDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.id
     *
     * @mbggenerated Thu Jun 22 11:43:29 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.version
     *
     * @mbggenerated Thu Jun 22 11:43:29 CST 2017
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.delete_flag
     *
     * @mbggenerated Thu Jun 22 11:43:29 CST 2017
     */
    private Boolean deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.valid_flag
     *
     * @mbggenerated Thu Jun 22 11:43:29 CST 2017
     */
    private Boolean validFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.sort
     *
     * @mbggenerated Thu Jun 22 11:43:29 CST 2017
     */
    private Long sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.name
     *
     * @mbggenerated Thu Jun 22 11:43:29 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.id
     *
     * @return the value of authority.id
     *
     * @mbggenerated Thu Jun 22 11:43:29 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.id
     *
     * @param id the value for authority.id
     *
     * @mbggenerated Thu Jun 22 11:43:29 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.version
     *
     * @return the value of authority.version
     *
     * @mbggenerated Thu Jun 22 11:43:29 CST 2017
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.version
     *
     * @param version the value for authority.version
     *
     * @mbggenerated Thu Jun 22 11:43:29 CST 2017
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.delete_flag
     *
     * @return the value of authority.delete_flag
     *
     * @mbggenerated Thu Jun 22 11:43:29 CST 2017
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.delete_flag
     *
     * @param deleteFlag the value for authority.delete_flag
     *
     * @mbggenerated Thu Jun 22 11:43:29 CST 2017
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.valid_flag
     *
     * @return the value of authority.valid_flag
     *
     * @mbggenerated Thu Jun 22 11:43:29 CST 2017
     */
    public Boolean getValidFlag() {
        return validFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.valid_flag
     *
     * @param validFlag the value for authority.valid_flag
     *
     * @mbggenerated Thu Jun 22 11:43:29 CST 2017
     */
    public void setValidFlag(Boolean validFlag) {
        this.validFlag = validFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.sort
     *
     * @return the value of authority.sort
     *
     * @mbggenerated Thu Jun 22 11:43:29 CST 2017
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.sort
     *
     * @param sort the value for authority.sort
     *
     * @mbggenerated Thu Jun 22 11:43:29 CST 2017
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.name
     *
     * @return the value of authority.name
     *
     * @mbggenerated Thu Jun 22 11:43:29 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.name
     *
     * @param name the value for authority.name
     *
     * @mbggenerated Thu Jun 22 11:43:29 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}