package com.mybatis.core.domain;

import com.mybatis.common.domain.BaseDomain;

public class Menu extends BaseDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.version
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.delete_flag
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    private Boolean deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.valid_flag
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    private Boolean validFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.sort
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    private Long sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.name
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.label
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.url
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.icon
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.style
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    private String style;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.cls
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    private String cls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.abstraction
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    private String abstraction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.views
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    private String views;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.active
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    private Boolean active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.resolve
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    private String resolve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.force_hide
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    private Boolean forceHide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.parent_id
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    private String parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.id
     *
     * @return the value of menu.id
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.id
     *
     * @param id the value for menu.id
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.version
     *
     * @return the value of menu.version
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.version
     *
     * @param version the value for menu.version
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.delete_flag
     *
     * @return the value of menu.delete_flag
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.delete_flag
     *
     * @param deleteFlag the value for menu.delete_flag
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.valid_flag
     *
     * @return the value of menu.valid_flag
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public Boolean getValidFlag() {
        return validFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.valid_flag
     *
     * @param validFlag the value for menu.valid_flag
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public void setValidFlag(Boolean validFlag) {
        this.validFlag = validFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.sort
     *
     * @return the value of menu.sort
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.sort
     *
     * @param sort the value for menu.sort
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.name
     *
     * @return the value of menu.name
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.name
     *
     * @param name the value for menu.name
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.label
     *
     * @return the value of menu.label
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.label
     *
     * @param label the value for menu.label
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.url
     *
     * @return the value of menu.url
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.url
     *
     * @param url the value for menu.url
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.icon
     *
     * @return the value of menu.icon
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.icon
     *
     * @param icon the value for menu.icon
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.style
     *
     * @return the value of menu.style
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.style
     *
     * @param style the value for menu.style
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public void setStyle(String style) {
        this.style = style == null ? null : style.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.cls
     *
     * @return the value of menu.cls
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public String getCls() {
        return cls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.cls
     *
     * @param cls the value for menu.cls
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public void setCls(String cls) {
        this.cls = cls == null ? null : cls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.abstraction
     *
     * @return the value of menu.abstraction
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public String getAbstraction() {
        return abstraction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.abstraction
     *
     * @param abstraction the value for menu.abstraction
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public void setAbstraction(String abstraction) {
        this.abstraction = abstraction == null ? null : abstraction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.views
     *
     * @return the value of menu.views
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public String getViews() {
        return views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.views
     *
     * @param views the value for menu.views
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public void setViews(String views) {
        this.views = views == null ? null : views.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.active
     *
     * @return the value of menu.active
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.active
     *
     * @param active the value for menu.active
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.resolve
     *
     * @return the value of menu.resolve
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public String getResolve() {
        return resolve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.resolve
     *
     * @param resolve the value for menu.resolve
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public void setResolve(String resolve) {
        this.resolve = resolve == null ? null : resolve.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.force_hide
     *
     * @return the value of menu.force_hide
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public Boolean getForceHide() {
        return forceHide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.force_hide
     *
     * @param forceHide the value for menu.force_hide
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public void setForceHide(Boolean forceHide) {
        this.forceHide = forceHide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.parent_id
     *
     * @return the value of menu.parent_id
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.parent_id
     *
     * @param parentId the value for menu.parent_id
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

}