package com.mybatis.core.domain;

import com.mybatis.common.domain.BaseDomain;

public class RequestMap extends BaseDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_map.id
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_map.version
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_map.delete_flag
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    private Boolean deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_map.valid_flag
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    private Boolean validFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_map.sort
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    private Long sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_map.url
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_map.authority
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    private String authority;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_map.id
     *
     * @return the value of request_map.id
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_map.id
     *
     * @param id the value for request_map.id
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_map.version
     *
     * @return the value of request_map.version
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_map.version
     *
     * @param version the value for request_map.version
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_map.delete_flag
     *
     * @return the value of request_map.delete_flag
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_map.delete_flag
     *
     * @param deleteFlag the value for request_map.delete_flag
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_map.valid_flag
     *
     * @return the value of request_map.valid_flag
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public Boolean getValidFlag() {
        return validFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_map.valid_flag
     *
     * @param validFlag the value for request_map.valid_flag
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public void setValidFlag(Boolean validFlag) {
        this.validFlag = validFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_map.sort
     *
     * @return the value of request_map.sort
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_map.sort
     *
     * @param sort the value for request_map.sort
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_map.url
     *
     * @return the value of request_map.url
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_map.url
     *
     * @param url the value for request_map.url
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_map.authority
     *
     * @return the value of request_map.authority
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public String getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_map.authority
     *
     * @param authority the value for request_map.authority
     *
     * @mbggenerated Thu Jun 29 14:12:21 CST 2017
     */
    public void setAuthority(String authority) {
        this.authority = authority == null ? null : authority.trim();
    }
}