package com.mybatis.auth.domain;

import com.mybatis.common.domain.BaseDomain;

public class Function extends BaseDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_function.id
     *
     * @mbggenerated Thu Jun 22 10:08:17 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_function.name
     *
     * @mbggenerated Thu Jun 22 10:08:17 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_function.parent_id
     *
     * @mbggenerated Thu Jun 22 10:08:17 CST 2017
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_function.url
     *
     * @mbggenerated Thu Jun 22 10:08:17 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_function.serial_num
     *
     * @mbggenerated Thu Jun 22 10:08:17 CST 2017
     */
    private Integer serialNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_function.accordion
     *
     * @mbggenerated Thu Jun 22 10:08:17 CST 2017
     */
    private Integer accordion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_function.id
     *
     * @return the value of auth_function.id
     *
     * @mbggenerated Thu Jun 22 10:08:17 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_function.id
     *
     * @param id the value for auth_function.id
     *
     * @mbggenerated Thu Jun 22 10:08:17 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_function.name
     *
     * @return the value of auth_function.name
     *
     * @mbggenerated Thu Jun 22 10:08:17 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_function.name
     *
     * @param name the value for auth_function.name
     *
     * @mbggenerated Thu Jun 22 10:08:17 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_function.parent_id
     *
     * @return the value of auth_function.parent_id
     *
     * @mbggenerated Thu Jun 22 10:08:17 CST 2017
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_function.parent_id
     *
     * @param parentId the value for auth_function.parent_id
     *
     * @mbggenerated Thu Jun 22 10:08:17 CST 2017
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_function.url
     *
     * @return the value of auth_function.url
     *
     * @mbggenerated Thu Jun 22 10:08:17 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_function.url
     *
     * @param url the value for auth_function.url
     *
     * @mbggenerated Thu Jun 22 10:08:17 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_function.serial_num
     *
     * @return the value of auth_function.serial_num
     *
     * @mbggenerated Thu Jun 22 10:08:17 CST 2017
     */
    public Integer getSerialNum() {
        return serialNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_function.serial_num
     *
     * @param serialNum the value for auth_function.serial_num
     *
     * @mbggenerated Thu Jun 22 10:08:17 CST 2017
     */
    public void setSerialNum(Integer serialNum) {
        this.serialNum = serialNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_function.accordion
     *
     * @return the value of auth_function.accordion
     *
     * @mbggenerated Thu Jun 22 10:08:17 CST 2017
     */
    public Integer getAccordion() {
        return accordion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_function.accordion
     *
     * @param accordion the value for auth_function.accordion
     *
     * @mbggenerated Thu Jun 22 10:08:17 CST 2017
     */
    public void setAccordion(Integer accordion) {
        this.accordion = accordion;
    }
}